services:
  metasim:
    user: ${DOCKER_UID}:${DOCKER_GID}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - http_proxy=${PROXY}
        - https_proxy=${PROXY}
        - DOCKER_UID=${DOCKER_UID:-1000}
        - DOCKER_GID=${DOCKER_GID:-1000}
        - DOCKER_USER=${DOCKER_USER:-user}
    container_name: metasim
    privileged: true
    runtime: nvidia
    environment:
      - DISPLAY=${DISPLAY}
      - LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu
      ## Below is for IsaacSim/IsaacLab Accept EULA, see:
      ## - https://isaac-sim.github.io/IsaacLab/main/source/deployment/docker.html#running-pre-built-isaac-lab-container
      ## - https://docs.omniverse.nvidia.com/isaacsim/latest/installation/install_python.html#running-isaac-sim
      - ACCEPT_EULA=Y
      - PRIVACY_CONSENT=Y
      - OMNI_KIT_ACCEPT_EULA=YES
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /usr/local/cuda:/usr/local/cuda
      - ./:/home/${DOCKER_USER}/RoboVerse
    tty: true  # Keeps the container running interactively
