defaults:
  - _self_
  - train: null

experiment:
  multi_gpu: False
  device_id: 0
  sim_device: "cuda:0"
  rl_device: "cuda:0"
  seed: 42
  output_name: ${train.task_name}
  debug: False
  checkpoint: null
  resume_training: False
  use_wandb: False

environment:
  num_envs: 32 # XXX: use inheritance from hydra in the future
  headless: False
  # Options: "isaacgym", "mujoco", or "isaaclab"
  sim_name: "isaacgym"
  rgb_observation: False

wandb:
  project: "roboverse"
  entity: "chengtianyue"
  mode: "disabled"

hydra:
  run:
    dir: .
