defaults:
  - ../default

task_name: "CloseBox"
robot_name: "franka"

algo: "sac"

action_space: 9
observation_space:
  shape: [10]
observation_shape: [10]

sac:
  action_num: 9
  multi_gpu: ${experiment.multi_gpu}
  num_actors: 32
  replay_buffer_size: 1000000
  reward_scale: 1.0
  initial_temperature: 0.1
  critic_tau: 0.01
  normalize_priv: True
  priv_info_stage2: True
  priv_info: True
  lr: 0.003
  gamma: 0.99
  tau: 0.95
  batch_size: 64
  network:
    mlp:
      units: [32, 32]
